// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: TestUPS

#ifndef _TESTUPS_UI_H
#define _TESTUPS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart2_Xaxis;
extern lv_obj_t * ui_Chart2_Yaxis1;
extern lv_obj_t * ui_Chart2_Yaxis2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Spinbox1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Spinbox2;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
